#98-user detail layout
boostcampth/boostcamp3_D pull request #102
Opened 2019-02-12 11:33 UTC by ro0opf

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
* layout 생성
* dialog class 생성

### Other information (e.g. related issues)
* viewmodel 연결 필요

![kakaotalk_20190212_203302178](https://user-images.githubusercontent.com/34717634/52632646-6d80a480-2f05-11e9-8ca8-f81942e67473.jpg)

resolved #98

2019-02-12 13:00 UTC, wjddnwls918 commented
LGTM

2019-02-13 01:14 UTC, Zi-Yun requested changes

2019-02-13 01:14 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardPreviewDialog.java
> +        View view = inflater.inflate(R.layout.board_preview_dialog, container, false);
데이터 바인딩을 사용하지 않은 이유가 있을까요?

2019-02-13 01:22 UTC, Zi-Yun requested changes

2019-02-13 01:22 UTC, Jiyunn commented on app/src/main/res/layout/user_detail_dialog.xml
> +    android:orientation="vertical">
유효하지 않은 속성은 지워주셔도 될 것 같아요.

2019-02-13 05:56 UTC, wjddnwls918 approved these changes

2019-02-13 07:50 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardPreviewDialog.java
> +        View view = inflater.inflate(R.layout.board_preview_dialog, container, false);
수정했습니다.
8c9d4dc

2019-02-13 07:50 UTC, ro0opf commented on app/src/main/res/layout/user_detail_dialog.xml
> +    android:orientation="vertical">
수정했습니다

2019-02-13 08:37 UTC, Zi-Yun approved these changes

2019-02-13 08:37 UTC, merged