#82-Board_Search 레이아웃 생성
boostcampth/boostcamp3_D pull request #105
Opened 2019-02-12 14:17 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
- Board_Search 레이아웃 필요

### New behaviour
- 레이아웃 생성
- EditText 설정에 필요한 함수 /common/util 패키지 분류

### Other information (e.g. related issues)

<div>
<img src= https://user-images.githubusercontent.com/20276966/52641431-23ef8400-2f1c-11e9-915c-4b090e4f4983.jpg width = 30%/>
</div>
resolved #82

2019-02-12 16:43 UTC, Zi-Yun requested changes

2019-02-12 16:43 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/common/util/EditTextUtil.java
> +        editText.addTextChangedListener(new TextWatcher() {
`TextWatcher`를 사용하셨는데, 
만약에 해당 `EditText`에 글자 입력 시 몇 글자 입력했는지 보여주는 기능 등을 구현할때는 어떤식으로 해결하나요?
이 메소드를 사용할 경우 다른 기능을 추가하기위해 `TextWatcher`를 사용할 수 없다면 다른 방법을 고려하는 것이 좋을 것 같아요.

2019-02-12 16:44 UTC, Jiyunn commented on app/src/main/res/layout/board_search_activity.xml
> +            android:singleLine="true"
👍

2019-02-12 16:45 UTC, Zi-Yun requested changes

2019-02-12 16:45 UTC, Jiyunn commented on app/src/main/res/layout/board_search_activity.xml
> +            android:id="@+id/rcv_board_search"
`RecyclerView`의 아이디는 rv로 수정하는게 좋을 것 같아요.

2019-02-12 16:46 UTC, Zi-Yun approved these changes

2019-02-12 16:48 UTC, Zi-Yun requested changes

2019-02-12 16:48 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardSearchActivity.java
> +    public void initToolbar() {
메소드 이름을 맞추는게 좋을 것 같아요.
initToolbar or setupToolbar

2019-02-13 02:06 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/common/util/EditTextUtil.java
> +        editText.addTextChangedListener(new TextWatcher() {
f8e0a7bca4bdbce43a590251ac2dfe735c54fb83

2019-02-13 02:06 UTC, wjddnwls918 commented on app/src/main/res/layout/board_search_activity.xml
> +            android:id="@+id/rcv_board_search"
50396500d94e106e81600f0e730a95b6e686701e

2019-02-13 03:29 UTC, Zi-Yun approved these changes

2019-02-13 05:26 UTC, ro0opf approved these changes
LGTM

2019-02-13 05:26 UTC, ro0opf commented on app/src/main/AndroidManifest.xml
> +        <activity
위치가 밑에 있는게 좋을 것 같아요.
상관은 없지만 activity가 순서대로 있으면 좋지 않을까요??

2019-02-13 05:33 UTC, merged