#106-Board_Search 이벤트 연결
boostcampth/boostcamp3_D pull request #107
Opened 2019-02-12 14:31 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
- Board_Search 이벤트 연결 필요

### New behaviour
- Board_Search 이벤트 연결

### Other information (e.g. related issues)

resolved #106

2019-02-12 16:49 UTC, Zi-Yun reviewed
이슈번호가 다른 커밋이 함께 올라왔네요

2019-02-12 16:57 UTC, Zi-Yun requested changes

2019-02-12 16:57 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardNavigator.java
> +    default void onAddressSearchClicked() {};
클릭 이벤트에 대한 함수이름도 논의하는게 좋을 것 같아요.

2019-02-12 16:57 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +        if (mNavigator != null) {
뷰 모델에 빈 생성자 X
`mNavigator` setter X 
`mNavigator` 가 생성자에서 초기화 O

저런 경우라면 null 검사를 하지 않아도 괜찮은 걸로 알고 있는데 여기서 검사해주는 이유가 궁금합니다.

2019-02-12 16:57 UTC, Jiyunn commented on app/src/main/res/layout/board_search_activity.xml
> +            android:onClick="@{viewmodel::onAddressSearchClicked}"
사용하지 않는 View타입을 파라미터로 받는 이유가 있을까요?

2019-02-13 02:07 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +        if (mNavigator != null) {
08d03c430cb90c3e6249c433534bf52c81740f67

2019-02-13 02:07 UTC, wjddnwls918 commented on app/src/main/res/layout/board_search_activity.xml
> +            android:onClick="@{viewmodel::onAddressSearchClicked}"
2f61675b44318af5fd4200858248e64be2dca70f

2019-02-13 03:27 UTC, Zi-Yun approved these changes

2019-02-13 05:27 UTC, ro0opf approved these changes
LGTM

2019-02-13 05:55 UTC, merged