#121-추천 게시글 가져오기 기능 추가
boostcampth/boostcamp3_D pull request #127
Opened 2019-02-13 10:53 UTC by ro0opf

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
* 서버 API 추가
* board data class photo 필드 추가 (추천 게시글에 들어가는 이미지를 위해)
* 서버로 부터 받아오는 기능 구현

### Other information (e.g. related issues)

resolved #121

2019-02-13 13:20 UTC, wjddnwls918 approved these changes

2019-02-13 17:05 UTC, leeyc09 reviewed
싱글턴을 사용해야해요

2019-02-13 17:05 UTC, leeyc09 commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +        HomeAPI service = ServiceGenerator.createService(HomeAPI.class);
ServiceGenerator. createService 을 할 때마다 새로운 Retrofit 인스턴스가 생성되고 있어요!! 이렇게 하시면 안되요!!
https://github.com/googlesamples/android-architecture/blob/todo-mvvm-databinding/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/TasksRepository.java

여러 참고 코드가 있겠지만 네트워크 객체 처럼 비용이 큰 것들은 싱글턴으로 만들어서 인스턴스를 하나로 관리하는게 중요합니다.

2019-02-14 01:03 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +        HomeAPI service = ServiceGenerator.createService(HomeAPI.class);
https://github.com/boostcampth/boostcamp3_D/pull/130

수정했습니다.

2019-02-14 01:11 UTC, Zi-Yun requested changes

2019-02-14 01:11 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +                service.getRecommendBoards().subscribeOn(Schedulers.io())
`subScribeOn`메소드 호출하는 부분이 한 줄 아래로 내려오면 가독성이 더 향상될 것 같아요.

2019-02-14 01:11 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +                        .subscribe(users -> {
의논해서 결정한대로 data로 바꾸면 좋을 것 같네요.

2019-02-14 01:15 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +                service.getRecommendBoards().subscribeOn(Schedulers.io())
수정했습니다.
206d333

2019-02-14 01:15 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
> +                        .subscribe(users -> {
수정했습니다.
206d333

2019-02-14 01:20 UTC, Zi-Yun requested changes

2019-02-14 01:20 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
>          HomeAPI service = ServiceGenerator.createService(HomeAPI.class);
랭크와 추천게시물에서 같은 서비스 클래스를 사용하는거면 클래스의 멤버변수로 선언하면 어떨까요?/

2019-02-14 01:20 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/home/HomeViewModel.java
>          HomeAPI service = ServiceGenerator.createService(HomeAPI.class);
수정했습니다.
4e79266

2019-02-14 01:35 UTC, Zi-Yun approved these changes

2019-02-14 01:36 UTC, merged