#77-사용자 정보 전송 기능 추가.
boostcampth/boostcamp3_D pull request #128
Opened 2019-02-13 16:47 UTC by Jiyunn

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
* `ETAPI` -> `UserAPI`로 수정 후, 메소드 선언.
* `User`클래스의 score관련 프로퍼티를 serialize할때 건너뛰도록 `transient` 키워드 추가.
(프로퍼티 이름 :  scoreNormal, scoreGood, scoreGreat, scoreSum)
* 공통적으로 사용하는 String리소스의 이름을 코드 컨벤션에 맞게 변경.

#### 전송 로직
1. 마이페이지 수정화면 진입 시 데이터베이스에서 사용자 정보 조회.
2. 저장하기 클릭.
3. 사용자가 입력한 데이터가 제출 양식에 맞는 지 확인.
4. 서버로 전송.

### Other information (e.g. related issues)
resolved #77

2019-02-14 01:02 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/data/User.java
받을때도 무시하나요?

2019-02-14 01:12 UTC, wjddnwls918 approved these changes
전체적으로 LGTM

2019-02-14 01:33 UTC, ro0opf requested changes

2019-02-14 01:33 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/mypage/MyPageEditViewModel.java
> +    private CompositeDisposable disposable = new CompositeDisposable();
변수 이름 disposables로 변경이 필요합니다

2019-02-14 01:33 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/mypage/MyPageEditViewModel.java
> +                        .subscribe(result -> {
data로 바꾸는 건 어떨까요?

2019-02-14 01:33 UTC, ro0opf commented on app/src/main/res/layout/mypage_edit_activity.xml
> +        <import
이건 뭔가요?

2019-02-14 01:33 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/login/LoginActivity.java
> +    public void saveUser(long id, String name, String photo) {
kakao id 인가요 user id 인가요?

2019-02-14 01:39 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/data/User.java
홈 화면에서 유저 랭킹을 받아오는 subscribe메소드에서 로그를 찍어봤을때는 값이 들어왔었습니다.

2019-02-14 01:40 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/mypage/MyPageEditViewModel.java
> +    private CompositeDisposable disposable = new CompositeDisposable();
e5a2d2e
수정했습니다.

2019-02-14 01:40 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/mypage/MyPageEditViewModel.java
> +    private CompositeDisposable disposable = new CompositeDisposable();
ad16a8e
수정했습니다.

2019-02-14 01:40 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/mypage/MyPageEditViewModel.java
> +                        .subscribe(result -> {
ad16a8e
수정했습니다.

2019-02-14 01:44 UTC, Jiyunn commented on app/src/main/res/layout/mypage_edit_activity.xml
> +        <import
`andorid.view.View`클래스를 import하기위해 선언한 부분입니다.
사용자가 나이를 제대로 입력하지 않았을 경우 안내문을 띄우는 뷰의 visibility를 설정하기 위해 사용했습니다.

2019-02-14 01:51 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/login/LoginActivity.java
> +    public void saveUser(long id, String name, String photo) {
0ff6206
kakao_id입니다.
직관적으로 어떤 변수인지 알 수 있게 `User`클래스와 동일한 이름으로 수정했습니다.

2019-02-14 01:52 UTC, ro0opf approved these changes

2019-02-14 01:59 UTC, merged

2019-02-16 03:23 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/data/User.java
#136 issue.