#164-BoardSearch RecyclerView 아이템 클릭 이벤트
boostcampth/boostcamp3_D pull request #165
Opened 2019-02-16 16:43 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
- BoardSearch화면의 RecyclerView 아이템 터치 이벤트 필요.

### New behaviour
- RxBus를 활용한 이벤트 연결
- RxBus 예외 처리 
- BoardSearch로부터 얻어온 데이터를 BoardAdd에서 활용하여 게시글 작성
- BoardSearch화면에서 검색어를 입력하지 않았을 경우에 SnackBar 띄우기

### Other information (e.g. related issues)
resolved #164

2019-02-17 03:21 UTC, Zi-Yun requested changes

2019-02-17 03:21 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardAddActivity.java
> +                Float.parseFloat(mViewModel.getmLongitude()),
위경도는 double or flaot ?
타입을 통일하면 좋을 것 같아요.

2019-02-17 03:21 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
> +        RxBus.getInstance().getBus().subscribe((position) -> {
bus는 데이터 받고 바로 끝나니 따로 `CompositeDisposable`선언안하고 바로 dispose해줘도 좋을 것 같아요.

2019-02-17 03:21 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchAdapter.java
> +        holder.binding.getRoot().setOnClickListener(new View.OnClickListener() {
앗! `onBindView`메소드 보다 뷰 홀더 클래스에서 리스너를 달아주면 어떨까요?
`onBindViewHolder`메소드는 새로운 아이템이 스크롤되거나 데이터 변경이 일어날때마다 호출되기 때문에 리스너를 달아주는 작업이 불필요하게 발생할 수 있다는 글을 본 것 같아요.
[그 글](https://stackoverflow.com/questions/33845846/why-is-adding-an-onclicklistener-inside-onbindviewholder-of-a-recyclerview-adapt)

2019-02-17 03:24 UTC, Zi-Yun requested changes

2019-02-17 03:24 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardAddActivity.java
> +            SnackBarUtil.showSnackBar(binding.rlBoardAddLayout, R.string.board_add_snack_bar);
유틸 메소드로 사용하도록 변경한 점 좋네요 👍

2019-02-17 03:24 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
>          setObserver();
옵저버 설정하는 메소드의 경우 `setObserver`로 네이밍 하나요? 혹은 `initObserver` 로 하나요?

2019-02-17 03:26 UTC, Zi-Yun requested changes

2019-02-17 03:26 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +        Board board = new Board(title,
보드 객체를 생성하는 부분이  깔끔해져서 보기좋네요

2019-02-17 03:26 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +                                    if(mNavigator != null)
finish하는 부분은 라이브데이터 사용하기로 했던 것 같은데
이 방법이 더 괜찮은가요?

2019-02-17 03:43 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardAddActivity.java
> +                Float.parseFloat(mViewModel.getmLongitude()),
9ffcc75d18ffcf6e3e67802cf88e318e54ab9779

2019-02-17 03:44 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
>          setObserver();
@ro0opf  재혁님과 같이 얘기해 봐야겠네요

2019-02-17 04:28 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
> +        RxBus.getInstance().getBus().subscribe((position) -> {
바로 dispose시 실행이 되지 않네요

2019-02-17 04:30 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchAdapter.java
> +        holder.binding.getRoot().setOnClickListener(new View.OnClickListener() {
onBindView는 계속 호출된다길래 onCreateViewHolder에서 리스너를 한번 연결해 줬습니다.
88c6945

2019-02-17 04:33 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +                                    if(mNavigator != null)
아 그때 얘기를 했었군요 
근데 저는 이게 익숙한거 같네요

2019-02-17 04:51 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +                                    if(mNavigator != null)
#159 
이게 변수 상태 관찰하고 있다가 종료하는거죠?
어떤게 더 좋을까요

2019-02-17 04:53 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +                                    if(mNavigator != null)
어떠한 특정 조건을 만족했을 때 이벤트를 발생시키려면 라이브데이터가 좋을것같습니다
근데 단순 이벤트는 Navigator를 통해 하는것도 좋을것같네요

2019-02-17 09:18 UTC, ro0opf requested changes

2019-02-17 09:18 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +                                    if(mNavigator != null)
이 부분은 월요일날 만나서 얘기를 하는게 어떨까요?
livedata를 사용하면 현재 navigator가 사용된 부분을 전부 대체 가능할 것 같아요.

2019-02-17 09:18 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +    public void onDestroyBoardViewModel() {
하나의 view는 하나의 viewmodel을 가지니깐 
onDestroyViewModel이라고 변경해도 될 것 같아요.

2019-02-17 09:18 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +    private int mMinute;
board를 변수로 두는 건 어떨까요?
`private Board board = new Board();`
board에 getter, setter가 구현이 되어있으니 아래 getter, setter 부분도 지워도 되고
makeboard에서 board를 return 해줘도 될 것 같아요

2019-02-17 09:27 UTC, ro0opf requested changes

2019-02-17 09:27 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
>          setObserver();
이 부분도 내일 얘기해용
init 혹은 set으로 모든 부분을 통일하는게 낫겟네요.

2019-02-17 09:27 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
> +        RxBus.getInstance().sendBus(-1);
현재 Rxbus가 한 액티비티 내에서만 사용되는 것 같은데

` int curPosition = (int) position;`
                        `Intent resultIntent = new Intent();
                        resultIntent.putExtra("placeName", mViewModel.getDocuments().get(curPosition).getPlaceName());
                        resultIntent.putExtra("addressName", mViewModel.getDocuments().get(curPosition).getAddressName());
                        resultIntent.putExtra("x", mViewModel.getDocuments().get(curPosition).getX());
                        resultIntent.putExtra("y", mViewModel.getDocuments().get(curPosition).getY());
                        setResult(RESULT_OK, resultIntent);
                        finish();`
이 부분을 method로 따로 선언한 뒤
해당 부분을 onDestroy에 적어주는 것은 어떨까요?

2019-02-17 11:13 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +    public void onDestroyBoardViewModel() {
eb79244

2019-02-17 11:22 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/search/BoardSearchActivity.java
> +        RxBus.getInstance().sendBus(-1);
잘 이해가 가지 않네요

2019-02-17 11:24 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardViewModel.java
> +    private int mMinute;
그렇게하면 ViewModel에서는 getter setter가 없어지고 보드 객체 하나만 있어서 직관적이여 질 수 있지만, Board객체에 setter를 통해 입력하는 과정은 복잡해 질것 같네요

2019-02-18 01:46 UTC, ro0opf approved these changes

2019-02-18 03:14 UTC, Zi-Yun approved these changes

2019-02-18 05:27 UTC, merged