#20-daum map api
boostcampth/boostcamp3_D pull request #28
Opened 2019-01-31 10:10 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
- 다음 지도 연동
- 검색 및 게시글 생성 이벤트 작성

### Other information (e.g. related issues)

resolved #20

2019-01-31 13:23 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapViewModel.java
> +        Log.d("searchButton","hihihi");
테스트용 로그는 지워주면 좋을 것 같아요.

2019-01-31 13:24 UTC, Jiyunn commented on app/src/main/res/layout/map_fragment.xml
> +    <RelativeLayout
`ConstraintLayout`을 사용해서 구현하면 어떨까요?!
두 개의 레이아웃을 중첩하지 않고도 가능할 것 같아요.

2019-01-31 13:25 UTC, Zi-Yun commented on app/src/main/res/layout/map_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
xml 코드 스타일이 project로 설정되있는 것 같아요. 
default로 바꾸고 자동완성 부탁드려요.
`File -> Setting -> CodeStyle`에서 변경할 수 있습니당.

2019-01-31 13:31 UTC, Jiyunn commented on app/src/main/res/layout/map_fragment.xml
> +        <com.google.android.material.floatingactionbutton.FloatingActionButton
`FloatingActionButon`의 `app:useCompatPadding = true` 로 주면 알아서 적절한 거리만큼 margin이 주어집니당.

2019-01-31 13:31 UTC, Jiyunn commented on app/src/main/res/layout/map_fragment.xml
> +                android:layout_width="50dp"
조금 더 크기가 크면 좋을 것 같아요.
width와 height를 `wrap_content`로 주고,
`app:fabSize=normal`로 주면 보통 크기로 알아서 늘려줍니당.

2019-01-31 23:48 UTC, ro0opf requested changes

2019-01-31 23:48 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java
> +    private String getAppKey(Context context) {
getAppKey 메소드는 지워도 되지 않을까요

2019-02-01 01:21 UTC, boostcampth commented
rebuild please

2019-02-01 01:57 UTC, Zi-Yun approved these changes
👍 확인했어요.

2019-02-01 03:37 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapViewModel.java
> +        Log.d("searchButton","hihihi");
762651e5ec14777525ce57cc50a849ddcf9ea5af

2019-02-01 03:38 UTC, wjddnwls918 commented on app/src/main/res/layout/map_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
762651e5ec14777525ce57cc50a849ddcf9ea5af

2019-02-01 03:38 UTC, wjddnwls918 commented on app/src/main/res/layout/map_fragment.xml
> +                android:layout_width="50dp"
762651e5ec14777525ce57cc50a849ddcf9ea5af

2019-02-01 03:38 UTC, ro0opf approved these changes

2019-02-01 03:38 UTC, merged