#31-게시물 미리보기 구현
boostcampth/boostcamp3_D pull request #37
Opened 2019-02-01 09:20 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour

- 게시물 미리보기를 구현했습니다.
- layout 추가, BoardPreviewDialog 클래스 추가

### Other information (e.g. related issues)

resolved #31

2019-02-02 08:10 UTC, ro0opf requested changes

2019-02-02 08:10 UTC, ro0opf commented on app/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:3.0.0'
버전을 gradle project 수준에서 변수로 정의해주세요.

2019-02-02 08:10 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardPreviewDialog.java
> +                new ColorDrawable(android.graphics.Color.TRANSPARENT));
`Dialog dialog = getDialog();
        if(dialog != null) {
            int height = ViewGroup.LayoutParams.MATCH_PARENT;
            dialog.getWindow().setLayout(900 , height);
        }`

` setStyle(DialogFragment.STYLE_NO_TITLE, R.style.DialogTheme);`

위 같은 경우 다른 메소드에서 override하는 이유가 있나용??

2019-02-02 08:10 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java
> +        binding.ibShowBottomSheet.setOnClickListener(new View.OnClickListener() {
테스트로 용도로 만들어 놓으신 버튼 리스너는 지워도 될 것 같습니다.

2019-02-02 08:10 UTC, ro0opf commented on app/src/main/res/layout/board_preview_dialog.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
constraintlayout 속성을 이용하여 1depth로 구성하는건 어떨까요?
(1) 상,하,좌,우 가이드라인 속성
(2) 상단 가이드 라인 아래 CircleImageView 위치
(3) CircleImageView 가운데부터 view들 위치?
@Jiyunn

2019-02-02 08:10 UTC, ro0opf commented on app/src/main/res/layout/board_preview_dialog.xml
> +                android:text="혼밥 시러~"
tools:text로 변경하고
android:text에는 databinding을 이용해 넣는 것이 어떨까요?

2019-02-02 08:10 UTC, ro0opf commented on app/src/main/res/layout/board_preview_dialog.xml
> +                android:textSize="14sp"
textSize도 미리 dimens에 정의해놓는게 어떨까요?
@wjddnwls918 @Jiyunn

2019-02-02 10:02 UTC, wjddnwls918 commented on app/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:3.0.0'
7bb31b49f8c9cdcf295490f9a22edef7801d2643

2019-02-02 10:02 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapFragment.java
> +        binding.ibShowBottomSheet.setOnClickListener(new View.OnClickListener() {
9ee8fe4873b928839db568137867dae9e33cf50d

2019-02-02 10:03 UTC, wjddnwls918 commented on app/src/main/res/layout/board_preview_dialog.xml
> +                android:textSize="14sp"
협의가 필요할것 같습니다. 이전에 얘기 나왔던 거긴하네요

2019-02-02 10:03 UTC, wjddnwls918 commented on app/src/main/res/layout/board_preview_dialog.xml
> +                android:text="혼밥 시러~"
현재는 임시로 데이터를 넣은것이라 사용할때 수정이 필요할것 같습니다.

2019-02-02 10:08 UTC, wjddnwls918 commented on app/src/main/res/layout/board_preview_dialog.xml
> +                android:text="혼밥 시러~"
182a8713da1538d9b502f2a3eaa773a865493277

2019-02-02 10:19 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardPreviewDialog.java
> +                new ColorDrawable(android.graphics.Color.TRANSPARENT));
위치를 여러번 변경해봤는데 
아마 Fragment의 생명주기와 연관이 있는것 같네요
onCreate에서는 UI관련 작업을 할 수 없다네요

2019-02-03 06:02 UTC, ro0opf approved these changes

2019-02-03 06:23 UTC, Zi-Yun commented on app/src/main/res/layout/board_preview_dialog.xml
> +        app:layout_constraintHeight_percent="0.3"
이 속성은 어떤 역할을 하는 건가요?

2019-02-03 06:27 UTC, wjddnwls918 commented on app/src/main/res/layout/board_preview_dialog.xml
> +        app:layout_constraintHeight_percent="0.3"
부모 뷰의 크기에 따라 비율을 고정하고 싶어 넣었습니다.

2019-02-03 07:06 UTC, merged