#42-board fragment layout
boostcampth/boostcamp3_D pull request #44
Opened 2019-02-03 07:44 UTC by ro0opf

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
* bottomnavigation에서 게시글에 해당하는 fragment 레이아웃 생성
* 이미지 혹은 기능 구성 시 새로운 view가 들어가는 부분(recyclerview item 등)을 색상 처리해놨습니다. (android:background="#ffff92")

### Other information (e.g. related issues)

resolved #42

2019-02-04 03:25 UTC, wjddnwls918 approved these changes

2019-02-04 03:25 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardFragment.java
> +        return view;
여기 저희 리턴할때 return binding.getRoot(); 이렇게 하기로 했던거 같아요

2019-02-04 11:35 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/main/MainActivity.java
> +        ActivityUtils.addFragmentToActivity(getSupportFragmentManager(), HomeFragment.newInstance(), R.id.fl_main);
이 부분이 필요한 이유가 있나요?
`Home`탭이 가장 첫번째 인덱스라서 기본으로 선택된 탭이 `Home`이지 않나요?

2019-02-04 11:37 UTC, Zi-Yun requested changes

2019-02-04 11:37 UTC, Jiyunn commented on app/src/main/res/values/colors.xml
> +    <color name="colorWhite">#f9f9f9</color>
네이밍이 `android:color/white`인 (#FFFFFF)와 헷갈릴 수 있을 것 같아요.
그리고 `#F9F9F9`는 이미 `colorHungryGray`로 정의되어있네요.

2019-02-04 11:38 UTC, Jiyunn commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_large_padding">24dp</dimen>
동일한 값의 dimen을 여러개 정의한 이유가 있나요?
`space_large_margin`과 `space_large_padding`이 어디서 쓰이는지 차이가 무엇인지 궁금합니당.

2019-02-04 11:39 UTC, Jiyunn commented on app/src/main/res/values/strings.xml
> +    <string name="board_tv_other_board">내가 참여중인 게시글</string>
내가 참여중인 게시글의 정의한 이름이 조금 더 직관적이면 좋을 것 같아요.

2019-02-04 11:44 UTC, Zi-Yun requested changes

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +            android:background="@color/colorHungryGray"
`colorHungryGray`와 `colorWhite`의 값이 동일한 `#F9F9F9`입니당.
`colorWhite`대신에 미리 정의 된 `colorHungryGray`를 사용하면 좋을 것 같아요.

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginLeft="@dimen/space_medium_margin"
`marginLeft`보다는 `marginStart`를 사용하는 것을 어떨까요? (코드 컨벤션 참고)

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginRight="@dimen/space_medium_margin"
`marginRight`보다는 `marginEnd`를 사용하는 것을 어떨까요? (코드 컨벤션 참고)

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginBottom="@dimen/space_medium_margin"
4방향의 margin이 모두 같은 값인데 `android:layout_margin=`속성을 사용하지 않고
각각 적어준 이유가 있을까요?

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +                    app:layout_constraintLeft_toLeftOf="parent"
이 경우에도 `constraintStart`를 사용하는 게 좋을 것 같아요.

2019-02-04 11:44 UTC, Jiyunn commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginLeft="@dimen/space_medium_margin"
여기도 `marginStart`, `marginEnd`로 사용하는 건 어떨까요?

2019-02-05 05:17 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/main/MainActivity.java
> +        ActivityUtils.addFragmentToActivity(getSupportFragmentManager(), HomeFragment.newInstance(), R.id.fl_main);
저도 기본으로 선택되는 건줄 알았는데 선택이 안되더라구용..
그래서 수동으로 적어줬습니다.

2019-02-05 05:22 UTC, ro0opf commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_large_padding">24dp</dimen>
margin 같은 경우 객체 외부 여백을 , padding 같은 경우 객체 내부 여백을 정의하기 위해 사용됩니다. recyclerview내 item layout을 정의할 때 padding을 이용하려고 합니다.

2019-02-05 05:32 UTC, ro0opf commented on app/src/main/java/com/teamdonut/eatto/ui/board/BoardFragment.java
> +        return view;
수정했습니다!
755d97f

2019-02-05 05:32 UTC, ro0opf commented on app/src/main/res/values/colors.xml
> +    <color name="colorWhite">#f9f9f9</color>
수정했습니다!
62f98ab

2019-02-05 05:32 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +            android:background="@color/colorHungryGray"
수정했습니다.
62f98ab

2019-02-05 05:33 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginLeft="@dimen/space_medium_margin"
수정했습니다.
fe03f74

2019-02-05 05:33 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +                    app:layout_constraintLeft_toLeftOf="parent"
수정했습니다.
fe03f74

2019-02-05 05:33 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginRight="@dimen/space_medium_margin"
수정했습니다.
fe03f74

2019-02-05 05:34 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginBottom="@dimen/space_medium_margin"
뷰 위치를 이동하며 적절한 위치를 찾다보니 모두 다 같은 값이 들어가게 되었네요.
수정했습니다!
fe03f74

2019-02-05 05:34 UTC, ro0opf commented on app/src/main/res/layout/board_fragment.xml
> +                    android:layout_marginLeft="@dimen/space_medium_margin"
수정했습니다.
fe03f74

2019-02-05 05:38 UTC, ro0opf commented on app/src/main/res/values/strings.xml
> +    <string name="board_tv_other_board">내가 참여중인 게시글</string>
수정했습니다.
3cf25da

2019-02-05 06:30 UTC, Zi-Yun commented on app/src/main/res/layout/board_fragment.xml
> +            android:background="@color/colorHungryGray"
Colorwhite의 경우 안드로이드에서 제공해주는
android:color/white가 있습니당
동일한 #Ffffff색상코드라면 저걸 사용하는건 어떨까요?

2019-02-05 07:10 UTC, Zi-Yun approved these changes

2019-02-05 07:14 UTC, merged