#34-Add bottom sheet
boostcampth/boostcamp3_D pull request #51
Opened 2019-02-04 15:51 UTC by Jiyunn

### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

### New behaviour
* `BottomSheet`를 `MapFragment`에 추가했습니다.

### Other information (e.g. related issues)
* `RecyclerView`에 필요한 클래스들은 추후에 추가할 예정입니다.

2019-02-04 16:10 UTC, wjddnwls918 approved these changes

2019-02-04 16:10 UTC, wjddnwls918 commented on app/src/main/res/layout/map_bottom_sheet.xml
> +            app:layout_constraintEnd_toStartOf="@+id/ib_down"
dimen 정의에 대해 언제한번 얘기가 필요할것 같네요

2019-02-05 04:12 UTC, Jiyunn commented on app/src/main/res/layout/map_bottom_sheet.xml
> +            app:layout_constraintEnd_toStartOf="@+id/ib_down"
넵

2019-02-05 06:00 UTC, ro0opf requested changes

2019-02-05 06:00 UTC, ro0opf commented on app/src/main/res/layout/board_add_activity.xml
> +            <com.appyvet.materialrangebar.RangeBar xmlns:app="http://schemas.android.com/apk/res-auto"
`xmlns:app="http://schemas.android.com/apk/res-auto"`
중복 정의되어있습니다.

2019-02-05 06:00 UTC, ro0opf commented on app/src/main/res/layout/map_bottom_sheet.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
`xmlns:android="http://schemas.android.com/apk/res/android"`
해당 부분을 layout에 통일해주는게 어떨까요

2019-02-05 06:00 UTC, ro0opf commented on app/src/main/res/layout/map_bottom_sheet.xml
> +        android:background="#E6FFFFFF">
colors.xml에 정의하는게 어떨까요?

2019-02-05 06:00 UTC, ro0opf commented on app/src/main/res/layout/map_fragment.xml
>              android:layout_marginTop="8dp"
dimens에 정의한 값을 이용하는건 어떨까요?

2019-02-05 12:35 UTC, Jiyunn commented on app/src/main/res/layout/board_add_activity.xml
> +            <com.appyvet.materialrangebar.RangeBar xmlns:app="http://schemas.android.com/apk/res-auto"
앗 이건 제가 올린게 아니네요 ㅠ

2019-02-05 12:35 UTC, Jiyunn commented on app/src/main/res/layout/map_bottom_sheet.xml
> +        android:background="#E6FFFFFF">
임시로 해놓은 색상이라서 아직 정의하지 않았습니다.

2019-02-05 13:53 UTC, ro0opf approved these changes

2019-02-05 14:01 UTC, Jiyunn commented on app/src/main/res/layout/map_fragment.xml
>              android:layout_marginTop="8dp"
#acfd6b2

2019-02-05 14:01 UTC, ro0opf commented on app/src/main/res/layout/map_fragment.xml
>              android:layout_marginTop="8dp"
acfd6b2

2019-02-05 14:04 UTC, Jiyunn commented on app/src/main/res/layout/map_bottom_sheet.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
4fa6d64 수정했습니다.

2019-02-05 14:13 UTC, merged