#57-Board_Detail 레이아웃 생성
boostcampth/boostcamp3_D pull request #58
Opened 2019-02-07 11:33 UTC by wjddnwls918

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

- Board Detail 레이아웃 필요

### New behaviour

- Map fragment에서 BoardAdd 이벤트 연결
- Board Detail 레이아웃 생성

### Other information (e.g. related issues)
<div>

<img src = https://user-images.githubusercontent.com/20276966/52408943-66c5ec00-2b17-11e9-82de-e782ba02dbcf.jpg width = "50%"/>
</div>
resolved #57

2019-02-10 07:46 UTC, ro0opf requested changes
고생하셨어요 우진님!!

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/values/strings.xml
> +    <string name="board_btn_input_comment">작성</string>
board_detail_btn_input_comment로 변경하고 상단에 `<!--board_detail-->` 을 적어주는게 어떨까요?
board화면과 board_detail화면이 혼동될 것 같습니다.

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/values/dimens.xml
> +    <dimen name="board_detail_static_edittext_size">30dp</dimen>
`<!-- Board_detail -->` 로 구분해주는건 어떨까요?

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/values/colors.xml
> +    <color name="colorBorderColor">#D0D0D0</color>
위 색상도 `<!-- Board_detail-->` 아래 넣으면 더 좋을 것 같아요

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/layout/board_detail_activity.xml
> +            <FrameLayout
Border를 View로 주는건 어떨까요?

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/layout/board_detail_activity.xml
> +
이 부분은 아직 저희끼리 얘기를 해봐야할 것 같은데,
화면 전체 스크롤이 가능한건가요??
@Jiyunn  @wjddnwls918 
저는 comment만 스크롤이 가능한 화면으로 생각했었어요.

2019-02-10 07:46 UTC, ro0opf commented on app/src/main/res/layout/board_detail_activity.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
현재 ScrollView 안에 Relative 안에 다수의 ConstraintLayout으로 구성되어있는 것 같습니다. 하나의 ConstraintLayout안에 GuideLine 혹은 Barriers를 이용하여 Layout을 정의하는건 어떨까요?

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/values/strings.xml
> +    <string name="board_btn_input_comment">작성</string>
a90c9c9eae5c98d029b4e7f8934468c025c97330

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="board_detail_static_edittext_size">30dp</dimen>
a90c9c9eae5c98d029b4e7f8934468c025c97330

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/values/colors.xml
> +    <color name="colorBorderColor">#D0D0D0</color>
a90c9c9eae5c98d029b4e7f8934468c025c97330

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/layout/board_detail_activity.xml
> +            <FrameLayout
1165af941e9be1a5dfa6c39f897c6252faf4128f

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/layout/board_detail_activity.xml
> +
a346bfb7233a32a0d38e78e6b19acfd551f775a7

2019-02-10 11:01 UTC, wjddnwls918 commented on app/src/main/res/layout/board_detail_activity.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
a346bfb7233a32a0d38e78e6b19acfd551f775a7

2019-02-10 12:06 UTC, Jiyunn commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapViewModel.java
> +    void setNavigator(MapNavigator navigator) {
navigator가 한번 초기화 후 변경되야하는게 아니라면 생성자로 받으면 어떨까요?

2019-02-10 12:09 UTC, Zi-Yun requested changes

2019-02-10 12:09 UTC, Jiyunn commented on app/src/main/res/values/dimens.xml
> +    <dimen name="board_tv_detail">12sp</dimen>
dimen이름을 정의할 때 `space_~`를 붙여서 하는 건 어떨까요? 코드 컨벤션을 참고해주세용

2019-02-10 12:09 UTC, Jiyunn commented on app/src/main/res/values/dimens.xml
>      <dimen name="board_item_to_item_distance_margin">15sp</dimen>
특별한 이유가 없다면 dp로 주는건 어떨까요?

2019-02-10 12:39 UTC, wjddnwls918 commented on app/src/main/res/values/dimens.xml
>      <dimen name="board_item_to_item_distance_margin">15sp</dimen>
텍스트라 일관되게 설정에따라 커질수 있게 sp로 했습니다

2019-02-10 12:40 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapViewModel.java
> +    void setNavigator(MapNavigator navigator) {
https://github.com/googlesamples/android-architecture/tree/todo-mvvm-databinding/ 
를 참고해서 했는데 제생각에도 그게 편할것같네요

2019-02-10 13:01 UTC, wjddnwls918 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="board_tv_detail">12sp</dimen>
5576494d1938a7f7163b913e048e92cadd2eab77

2019-02-10 13:01 UTC, wjddnwls918 commented on app/src/main/java/com/teamdonut/eatto/ui/map/MapViewModel.java
> +    void setNavigator(MapNavigator navigator) {
79a6605ef6468a6e2188ba5fcb1e86b63d445d4a

2019-02-10 22:55 UTC, ro0opf approved these changes

2019-02-11 01:07 UTC, wjddnwls918 commented on app/src/main/res/values/dimens.xml
>      <dimen name="board_item_to_item_distance_margin">15sp</dimen>
b4ea35081a357ef0d0dfcc5af347a955f68f63de

2019-02-11 01:14 UTC, Zi-Yun approved these changes

2019-02-11 01:17 UTC, merged